theme: jekyll-theme-leap-day
title: Software Stack for Scalable Heterogeneous NISQ Cluster (SSSHNC)
show_downloads: false
description: The official website of PPoSS SSSHNC project.
google_analytics: true

root: /NSF_Conference_Site
pages:
- title: Home
  url: /
- title: Workshop on Quantum Applications
  url: /conference
- title: Pay Fees
  url: /payment